DondeEstudiar/Controllers/AutocompleteController.cs
using DondeEstudiar.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DondeEstudiar.Entidades;
namespace DondeEstudiar.Controllers
{
    public class AutocompleteController : Controller
    {
        bd_dondeestudiarEntities db = new bd_dondeestudiarEntities();

        public ActionResult Index()
        {
            return View();
        }

        public JsonResult GetCarrera(string search) {

            List<CarrerasModel> carreras =
                db.tb_carreras.Where(x =>
                x.nom_carrera.Contains(search))
                .Select(x => new CarrerasModel
                {
                    id_carrera = x.id_carrera,
                    nom_carrera = x.nom_carrera
                }).Take(5).ToList();
            return new JsonResult { Data = carreras, JsonRequestBehavior = JsonRequestBehavior.AllowGet };
        }
        public JsonResult GetArea(string search)
        {

            List<AreasModel> areas =
                db.tb_areas.Where(x =>
                x.desc_area.Contains(search))
                .Select(x => new AreasModel
                {
                    id_area = x.id_area,
                    desc_area = x.desc_area
                }).Take(5).ToList();
            return new JsonResult { Data = areas, JsonRequestBehavior = JsonRequestBehavior.AllowGet };
        }


        public JsonResult getInstitucion(string search)
        {

            List<InstitucionesModel> instituciones =
                db.tb_instituciones.Where(x =>
                x.nom_institucion.Contains(search))
                .Select(x => new InstitucionesModel
                {
                    id_institucion = x.id_institucion,
                    nom_institucion = x.nom_institucion
                }).Take(5).ToList();
            return new JsonResult { Data = instituciones, JsonRequestBehavior = JsonRequestBehavior.AllowGet };
        }

        public JsonResult GetUbigeo(string search)
        {


            List<UbigeoModel> ubigeos =
                db.tb_ubigueos.Where(x =>
                x.desc_dep.StartsWith(search))
                .Select(x => new UbigeoModel 
                {
                    cod_dep = x.cod_dep,
                    desc_dep = x.desc_dep,
                    
                }).GroupBy(x => x.desc_dep).Select(grp => grp.FirstOrDefault()).ToList();
            return new JsonResult { Data = ubigeos, JsonRequestBehavior = JsonRequestBehavior.AllowGet };
        }

        public JsonResult GetPOPCarrera(string searchTerm) {
            var ListaCarrera = db.tb_carreras.Take(5).ToList();

            if (searchTerm != null) {
                ListaCarrera = db.tb_carreras.Where(x =>
                x.nom_carrera.Contains(searchTerm)).Take(5).ToList();
            }

            var modifiedData = ListaCarrera.Select(x => new {
                id = x.nom_carrera,
                text = x.nom_carrera
            });

            return Json(modifiedData, JsonRequestBehavior.AllowGet);
        }
        public JsonResult GetPOPInstitucion(string searchTerm)
        {
            var ListaInsti = db.tb_instituciones.Take(5).ToList();

            if (searchTerm != null)
            {
                ListaInsti = db.tb_instituciones.Where(x =>
                x.nom_institucion.Contains(searchTerm)).Take(5).ToList();
            }

            var modifiedData = ListaInsti.Select(x => new {
                id = x.nom_institucion,
                text = x.nom_institucion
            });

            return Json(modifiedData, JsonRequestBehavior.AllowGet);
        }
        public JsonResult GetPOPUbicacion(string searchTerm)
        {
            var ListaUbicacion = db.tb_ubigueos.GroupBy(x => x.desc_dep).Select(grp => grp.FirstOrDefault()).Take(10).ToList();

            if (searchTerm != null)
            {
                ListaUbicacion = db.tb_ubigueos.Where(x =>
                x.desc_dep.Contains(searchTerm)).GroupBy(x => x.desc_dep).Select(grp => grp.FirstOrDefault()).Take(10).ToList();
            }

            var modifiedData = ListaUbicacion.Select(x => new {
                id = x.desc_dep,
                text = x.desc_dep
            });

            return Json(modifiedData, JsonRequestBehavior.AllowGet);
        }


    }
}

DondeEstudiar/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DondeEstudiarHost.Controllers;
using DondeEstudiar.Models;

namespace DondeEstudiarHost.Controllers
{
    public class HomeController : Controller
    {
        bd_dondeestudiarEntities db = new bd_dondeestudiarEntities();
        public ActionResult Index()
        {
            var lista = from p in db.det_sede_carrera
                            //where DbFunctions.TruncateTime(p.tb_paquete.fecha_compra) >= DbFunctions.TruncateTime(DateTime.Today)                     
                        select p ;

            return View(lista.ToList());
        }
        public ActionResult FiltroPreguntas(String carrera, String institucion, String ubicacion)
        {
            var lista = db.det_sede_carrera.Where
                (x => x.tb_carreras.nom_carrera.ToLower().Contains(carrera) && x.tb_sedes.tb_instituciones.nom_institucion.ToLower().Contains(institucion) &&
                x.tb_sedes.tb_ubigueos.desc_dep.ToLower().Contains(ubicacion));

            
            //Me trae las variables que filtro
            ViewBag.dtCarrera = carrera;
            ViewBag.dtInstitucion = institucion;
            ViewBag.dtUbicacion = ubicacion;

            return View(lista.ToList());
        }

        public ActionResult FiltroCards(String carrera, String institucion, String ubicacion)
        {
            var lista = db.det_sede_carrera.Where
                (x => x.tb_carreras.nom_carrera.ToLower().Contains(carrera) && x.tb_sedes.tb_instituciones.nom_institucion.ToLower().Contains(institucion) &&
                x.tb_sedes.tb_ubigueos.desc_dep.ToLower().Contains(ubicacion));


            //Me trae las variables que filtro
            ViewBag.dtCarrera = carrera;
            ViewBag.dtInstitucion = institucion;
            ViewBag.dtUbicacion = ubicacion;

            return View(lista.ToList());
        }


        public ActionResult Preguntas() {

            return View();
         }
        public ActionResult IndexCards(int pagina = 1)
        {
            var cantidadRegistrosPorPagina = 4; // parámetro
            var lista = db.det_sede_carrera.GroupBy(x => x.id_carrera).Select(grp => grp.FirstOrDefault()).OrderBy(x => x.tb_carreras.nom_carrera).Skip((pagina - 1) * cantidadRegistrosPorPagina).Take(cantidadRegistrosPorPagina).ToList();

            var totalDeRegistros = db.det_sede_carrera.GroupBy(x => x.id_carrera).Select(grp => grp.FirstOrDefault()).Count();


            var modelo = new BaseModelo();
            modelo.listaDetallesSedeCarrera = lista;
            modelo.PaginaActual = pagina;
            modelo.TotalDeRegistros = totalDeRegistros;
            modelo.RegistrosPorPagina = cantidadRegistrosPorPagina;

            ViewBag.totalDeRegistros = totalDeRegistros;
            return View(modelo);

        }


        public PartialViewResult Paginador(int pagina = 1)
        {
            var cantidadRegistrosPorPagina = 4;
            var lista = from p in db.det_sede_carrera
                        select p;
            var totalDeRegistros = lista.GroupBy(x => x.id_carrera).Select(grp => grp.FirstOrDefault()).Count();
            ViewBag.totalDeRegistros = totalDeRegistros;
            var modelo = new BaseModelo();
            modelo.listaDetallesSedeCarrera = lista.ToList();
            modelo.PaginaActual = pagina;
            modelo.TotalDeRegistros = totalDeRegistros;
            modelo.RegistrosPorPagina = cantidadRegistrosPorPagina;

            return PartialView(modelo);
        }
    }
}

DondeEstudiar/Views/Home/FiltroCards.cshtml
@model IEnumerable<DondeEstudiar.Models.det_sede_carrera>

@{
    ViewBag.Title = "FiltroCards";
}

<div class="form-row">
    <div class="col-lg-12 col-xs-8 col-sm-8 col-md-8">
        <div class="row">
            @foreach (var item in Model)
            {

                <div class="col-lg-6 col-md-6 mb-4">
                    <div class="card card-cascade card-ecommerce narrower">

                        <!--Card image-->
                        <div class="view overlay">
                            <img class="card-img-top" src="http://www.mcaproyectos.com/uploads/instituciones/@item.tb_sedes.tb_instituciones.logo" alt="">
                            <a>
                                <div class="mask rgba-white-slight"></div>
                            </a>
                        </div>
                        <!--/.Card image-->
                        <!--Card content-->
                        <div class="card-body text-center">
                            <!--Category & Title-->
                            <h5>@item.tb_carreras.nom_carrera</h5>
                            <h4 class="card-title"><strong><a href="">@item.tb_sedes.tb_instituciones.nom_institucion</a></strong></h4>

                            <!--Description-->
                            <p class="card-text" title="Ubicacion/Distrito">
                                <a title="Ubicacion/Distrito" class="px-2 fa-lg li-ic"><i class="fas fa-map-marker-alt"></i></a>
                                @item.tb_sedes.tb_ubigueos.desc_dep , @item.tb_sedes.tb_ubigueos.desc_dist
                            </p>





                            <!--Card footer-->
                            <div class="card-footer">
                                <span class="float-left">15 <a class="" data-toggle="tooltip" data-placement="top" title="Quick Look"><i class="fa fa-eye mr-3"></i></a></span>
                                <span class="float-right">
                                    10
                                    <a class="" data-toggle="tooltip" data-placement="top" title="Add to Wishlist"><i class="fa fa-heart"></i></a>
                                </span>
                            </div>

                        </div>
                        <!--/.Card content-->

                    </div>
                    <!-- Card Wider -->


                </div>


            }
            
        </div>
    </div>

</div>

DondeEstudiar/Views/Home/IndexCards.cshtml
@model DondeEstudiar.Models.BaseModelo


    @foreach (var item in Model.listaDetallesSedeCarrera@*.GroupBy(x => x.tb_carreras.id_carrera).Select(grp => grp.First())*@)

{
<div class="col-lg-6 col-md-6 mb-4">
    <div class="card card-cascade card-ecommerce narrower">
        <!--Card image-->
        <div class="view overlay">
            <img class="card-img-top" src="@item.tb_carreras.ruta_img" alt="">
            <a>
                <div class="mask rgba-white-slight"></div>
            </a>
        </div>
        <!--/.Card image-->
        <!--Card content-->
        <div class="card-body text-center">
            <!--Category & Title-->
            <h5>@item.tb_carreras.nom_carrera</h5>
            <h4 class="card-title"><strong><a href="">@item.tb_sedes.tb_instituciones.nom_institucion</a></strong></h4>
            <!--Description-->
            <p class="card-text" title="Ubicacion/Distrito">
                <a title="Ubicacion/Distrito" class="px-2 fa-lg li-ic"><i class="fas fa-map-marker-alt"></i></a>
                @item.tb_sedes.tb_ubigueos.desc_dep , @item.tb_sedes.tb_ubigueos.desc_dist
            </p>


            <!--Card footer-->
            <div class="card-footer">
                <span class="float-left">15 <a class="" data-toggle="tooltip" data-placement="top" title="Quick Look"><i class="fa fa-eye mr-3"></i></a></span>
                <span class="float-right">
                    10
                    <a class="" data-toggle="tooltip" data-placement="top" title="Add to Wishlist"><i class="fa fa-heart"></i></a>
                </span>
            </div>
        </div>
        <!--/.Card content-->
    </div>
    <!-- Card Wider -->

</div>
}

DondeEstudiar/Views/Home/Paginador.cshtml
@model DondeEstudiar.Models.BaseModelo
@{
    var cantidadPaginas = (int)Math.Ceiling((double)Model.TotalDeRegistros / Model.RegistrosPorPagina);
}

@{
    int Inicial = 1;
    var radio = 3;
    var cantidadMaximaDePaginas = radio * 2 + 1;
    int Final = (cantidadPaginas > cantidadMaximaDePaginas) ? cantidadMaximaDePaginas : cantidadPaginas;
    if (Model.PaginaActual > radio + 1)
    {
        Inicial = Model.PaginaActual - radio;
        if (cantidadPaginas > Model.PaginaActual + radio)
        {
            Final = Model.PaginaActual + radio;
        }
        else
        {
            Final = cantidadPaginas;
        }
    }
}

<div class="pagination-cs">
    <ul class="pagination pg-blue">

        <li class="page-item" onclick="paginar(this,1)">
            <a class="page-link">Primera</a>

        </li>
        @for (int i = Inicial; i <= Final; i++)
        {

            if (i == Model.PaginaActual)
            {
                <li class="page-item active" onclick="paginar(this,@i)">
                    <a class="page-link " >@i.ToString()</a>

                </li>
            }
            else
            {
                <li class="page-item" onclick="paginar(this,@i)">
                    <a class="page-link">@i.ToString()</a>

                </li>
            }
        }

          <li class="page-item" onclick="paginar(this,@cantidadPaginas)">
                    <a class="page-link">Ultima</a>

                </li>
    </ul>
</div>

<script src="~/Assets/js/jquery-3.2.1.min.js"></script>
<script src="~/Assets/js/jquery-ui.js"></script>
<script>
    function paginar(thi,index) {
       
        $(".page-item").removeClass("active");
        $(thi).addClass("active");

        var data = {pagina:index};
        $.ajax({
            type: 'POST',
            url: '/Home/IndexCards/',
            data: JSON.stringify(data),
            contentType: 'application/json',
            success: function (data) {
                console.log("success post");
                $("#rowCarreras").fadeOut(1000, function () {
                    $(this).css("display", "none");
                    $(this).html(data);
                });
                $("#rowCarreras").fadeIn(500);

            },
            error: function () {
                alert("error post");
            }
        });
    }

</script>

DondeEstudiar/Views/Home/Preguntas.cshtml
<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link href="~/AssetsB4-sinMD/css/preguntas.css" rel="stylesheet" />
    <link href="~/AssetsB4-sinMD/css/cards.css" rel="stylesheet" />
    <link href="~/AssetsB4-sinMD/css/estilos.css" rel="stylesheet" />
    <link href="~/AssetsB4-sinMD/css/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Assets/css/jquery-ui.css" rel="stylesheet" />
    <link href="~/Content/css/select2.min.css" rel="stylesheet" />
    <link href="~/Content/css/select2-bootstrap4.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.10/css/all.css" integrity="sha384-+d0P83n9kaQMCwj8F4RJB66tzIwOKmrdb46+porD/OvrJ+37WqIM7UoBtwHO6Nlg" crossorigin="anonymous">
    <style>
        @@-webkit-keyframes spin {
            0% {
                -webkit-transform: rotate(0deg);
            }

            100% {
                -webkit-transform: rotate(360deg);
            }
        }

        @@keyframes spin {
            0% {
                transform: rotate(0deg);
            }

            100% {
                transform: rotate(360deg);
            }
        }

        .load-page {
            border: 16px solid #f3f3f3;
            border-radius: 50%;
            border-top: 16px solid #e6840a;
            width: 120px;
            height: 120px;
            -webkit-animation: spin 10s linear infinite; /* Safari */
            animation: spin 1s linear infinite;
        }

        .modal {
            display: none;
            position: fixed;
            z-index: 1000;
            top: 0;
            left: 0;
            height: 100%;
            width: 100%;
            background-image: linear-gradient( rgb(89, 90, 95), rgba(84, 81, 79, 0.8) ), url();
        }

        /* When the body has the loading class, we turn
        the scrollbar off with overflow:hidden */
        body.loading .modal {
            overflow: hidden;
        }

        /* Anytime the body has the loading class, our
        modal element will be visible */
        body.loading .modal {
            display: block;
        }

        .block-c {
            display: block;
        }

        .none-c {
            display: none;
        }

        .btn-link {
            text-align: left;
            color: black !important;
            background: white !important;
        }

            .btn-link:hover {
                color: white !important;
                background: #527ac3 !important;
            }
    </style>

    <title>Donde Estudiar</title>
</head>
<body onsubmit="redirect()" class="bg-body">
    <div id="#CargaLoad" class="modal none-c">
        <div class="container">
            <div class="load-page responsive" style="
            /* text-align: center; */
            /* color: white; */
            margin-top: 21rem;
            margin-left: 30rem;
        ">

            </div>
            <h1 style="
            text-align: center;
            color: white;
            margin-top: 0rem;
        ">
                Estamos eligiendo las mejores opciones para ti...
            </h1>
        </div>
    </div>

    <section class="form-box">
        <div class="container">

            <div class="row">
                <div class="col-lg-12">
                    <div class="offset-md-3 col-sm-10 col-md-8 col-lg-6 form-wizard">

                        <!-- Form Wizard -->
                        <form role="form" action="@Url.Action("FiltroPreguntas","Home")" method="post" id="formulario" autocomplete=”off”>

                            <!--<h3>Que piensas estudiar?</h3>-->
                            <p>Te haremos algunas preguntas de acuerdo a eso te daremos las mejores opciones</p>

                            <!-- Form progress -->
                            <!-- <div class="form-wizard-steps form-wizard-tolal-steps-3">
                                <div class="form-wizard-progress">
                                    <div class="form-wizard-progress-line" data-now-value="12.25" data-number-of-steps="4" style="width: 12.25%;"></div>
                                </div>

                                <div class="form-wizard-step active">
                                    <div class="form-wizard-step-icon"><i class="fa fa-user" aria-hidden="true"></i></div>
                                    <p>Carrera</p>
                                </div>



                                <div class="form-wizard-step">
                                    <div class="form-wizard-step-icon"><i class="fa fa-location-arrow" aria-hidden="true"></i></div>
                                    <p>Institucion</p>
                                </div>



                                <div class="form-wizard-step">
                                    <div class="form-wizard-step-icon"><i class="fa fa-briefcase" aria-hidden="true"></i></div>
                                    <p>Economia</p>
                                </div>



                            </div> -->
                            <!-- Form progress -->
                            <!-- Form Step 1 -->
                            <fieldset>


                                <div class="form-group">
                                    <h4>¿Que carrera deseas estudiar?</h4>
                                    <select id="carrera" class="form-control" name="carrera" style="width: 100%">

                                    </select>
                                </div>

                                <div class="form-wizard-buttons">
                                    <button type="button" class="btn btn-next">Siguiente</button>
                                </div>
                            </fieldset>
                            <!-- Form Step 1 -->
                            <!-- Form Step 2 -->
                            <fieldset>


                                <div class="form-group">
                                    <h4>¿En que instituto o universidad te gustaria estudiar?</h4>
                                    <select id="institucion" class="form-control"  name="institucion" style="width: 100%">

                                    </select>
                                </div>

                                <div class="form-wizard-buttons">
                                    <button type="button" class="btn btn-next">
                                        Siguiente
                                    </button>
                                </div>
                            </fieldset>
                            <!-- Form Step 2 -->
                            <!-- Form Step 3 -->
                            <fieldset>



                                <div class="form-group">
                                    <h4>¿En donde te encuentras actualmente?</h4>
                                    <select id="ubicacion" class="form-control"  name="ubicacion" style="width: 100%">

                                    </select>
                                </div>
                                <div class="form-wizard-buttons">
                                    <button id="btn-Enviar" type="submit" class="btn btn-next">Enviar</button>
                                </div>
                            </fieldset>
                            <!-- Form Step 3 -->



                        </form>
                        <!-- Form Wizard -->
                    </div>
                </div>

            </div>

        </div>
    </section>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="~/AssetsB4-sinMD/js/jquery-3.3.1.min.js"></script>
    <script src="~/AssetsB4-sinMD/js/bootstrap.min.js"></script>
    <script src="~/AssetsB4-sinMD/js/preguntas.js"></script>
    <script src="~/Assets/js/jquery-ui.js"></script>
    <script src="~/Scripts/select2.min.js"></script>

   <script>
       $(document).ready(function () {
           $("#carrera").select2({
               placeholder: "Seleccione Carrera",
               theme: "bootstrap4",
               ajax: {
                   url: '@Url.Action("GetPOPCarrera", "Autocomplete")',
                   dataType: "json",
                   data: function (params) {
                       return {
                           searchTerm: params.term
                       };
                   },
                   processResults: function (data, params) {
                       return {
                           results: data
                       };
                   }
               }
           });
       });

           $(document).ready(function () {
           $("#institucion").select2({
               placeholder: "Seleccione Institución",
               theme: "bootstrap4",
               ajax: {
                   url: '@Url.Action("GetPOPInstitucion", "Autocomplete")',
                   dataType: "json",
                   data: function (params) {
                       return {
                           searchTerm: params.term
                       };
                   },
                   processResults: function (data, params) {
                       return {
                           results: data
                       };
                   }
               }
           });
       });

           $(document).ready(function () {
           $("#ubicacion").select2({
               placeholder: "Seleccione Ubicacion",
               theme: "bootstrap4",
               
               ajax: {
                   url: '@Url.Action("GetPOPUbicacion", "Autocomplete")',
                   dataType: "json",
                   data: function (params) {
                       return {
                           searchTerm: params.term
                       };
                   },
                   processResults: function (data, params) {
                       return {
                           results: data
                       };
                   }
               }
           });
       });
  
   </script>
    
    <script language="javascript" type="text/javascript">
        var formulario = document.getElementById('formulario'); // el id del formulario

        var redirect = function () {
            $(".modal").fadeToggle(8000, function () {

                $(".modal").removeClass("none-c");
                $(".modal").addClass("block-c");

            });
            setTimeout("document.getElementById('formulario').submit()", 8000)
        }
                    /*Cuando Carga la Pagina*/

    </script>
</body>
</html>